spring.application.name=pruebaSpring
server.port=9494

# JPA / Hibernate settings
#spring.jpa.database=mysql
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

# Database connection
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://localhost:3307/swapp16046
#spring.datasource.username=root
#spring.datasource.password=

spring.jpa.database=postgresql
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver
#Desde Spring Boot 3.1
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/ProyectoAlquiler
spring.datasource.username=postgres
spring.datasource.password=Abner
